[theme]
primaryColor = "#1E90FF"             # Blue for buttons and highlights
backgroundColor = "#FFFFFF"          # White background
secondaryBackgroundColor = "#F0F0F0" # Light gray for widgets
textColor = "#222222"                # Dark text
font = "sans serif"
